# Use an official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_PASSWORD your_password
ENV POSTGRES_DB your_database_name

# Copy the SQL initialization script to the container
# COPY init.sql /docker-entrypoint-initdb.d/
